/** 天气 SVG 图标 id（对应 assets/icons/weather/weather-{slug}-{dark|light}.svg） */
export type WeatherIconSlug =
  | 'sun'
  | 'sun-night'
  | 'partly-cloudy'
  | 'partly-cloudy-night'
  | 'few-clouds'
  | 'few-clouds-night'
  | 'cloudy'
  | 'cloudy-night'
  | 'overcast'
  | 'shower'
  | 'shower-night'
  | 'shower-heavy'
  | 'shower-heavy-night'
  | 'thunderstorm'
  | 'thunderstorm-heavy'
  | 'thunderstorm-hail'
  | 'rain-light'
  | 'rain-medium'
  | 'rain-heavy'
  | 'rain-storm'
  | 'rain-storm-heavy'
  | 'rain-storm-extreme'
  | 'rain-extreme'
  | 'drizzle'
  | 'rain-light-medium'
  | 'rain-medium-heavy'
  | 'rain-heavy-storm'
  | 'rain-storm-to-heavy'
  | 'rain-heavy-to-extreme'
  | 'rain'
  | 'freezing-rain'
  | 'sleet'
  | 'rain-snow'
  | 'snow-shower'
  | 'snow-shower-night'
  | 'snow-light'
  | 'snow-medium'
  | 'snow-heavy'
  | 'snow-storm'
  | 'snow-light-medium'
  | 'snow-medium-heavy'
  | 'snow-heavy-storm'
  | 'shower-sleet'
  | 'shower-sleet-night'
  | 'snow'
  | 'fog'
  | 'fog-dense'
  | 'fog-heavy'
  | 'fog-extreme'
  | 'fog-light'
  | 'fog-thick'
  | 'haze'
  | 'haze-moderate'
  | 'haze-severe'
  | 'haze-critical'
  | 'dust'
  | 'sand'
  | 'sandstorm'
  | 'sandstorm-heavy'
  | 'tornado'
  | 'typhoon'
  | 'hot'
  | 'cold'
  | 'unknown'

export type WeatherIconId = `weather-${WeatherIconSlug}`

export const WEATHER_ICON_LOADING: WeatherIconId = 'weather-unknown'

export function weatherIconId(slug: WeatherIconSlug): WeatherIconId {
  return `weather-${slug}`
}
