import type { Component } from 'vue'
import {
    AppWindow,
    ArrowDownAZ,
    ArrowDownFromLine,
    ArrowLeft,
    ArrowRight,
    ArrowUpToLine,
    BookOpen,
    Box,
    CalendarPlus,
    Car,
    Check,
    ChevronLeft,
    ChevronRight,
    CircleAlert,
    CircleHelp,
    Clock,
    Compass,
    Copy,
    Database,
    Download,
    EllipsisVertical,
    Eye,
    ExternalLink,
    Folder,
    FolderOpen,
    FolderPlus,
    Globe,
    Heart,
    Home,
    Image,
    Inbox,
    Layers,
    LayoutGrid,
    Link,
    List,
    Loader2,
    Maximize2,
    Minus,
    Palette,
    Pin,
    PinOff,
    Pencil,
    Plus,
    RefreshCw,
    RotateCcw,
    Save,
    Search,
    Share2,
    Settings,
    SlidersHorizontal,
    Smartphone,
    Sparkles,
    Square,
    SquareArrowUpLeft,
    Star,
    Sun,
    ThumbsUp,
    Trash2,
    TriangleAlert,
    User,
    Video,
    Volume2,
    VolumeX,
    X,
    Zap
} from '@lucide/vue'
import { CloudAbode } from './CloudAbode'
import { Github } from './Github'

/** 全局描边宽度（px），absoluteStrokeWidth 下视觉更一致 */
export const WW_ICON_STROKE = 1.5

export const wwIcons = {
    'app-window': AppWindow,
    'arrow-down-a-z': ArrowDownAZ,
    'arrow-down-from-line': ArrowDownFromLine,
    'arrow-left': ArrowLeft,
    'arrow-up-to-line': ArrowUpToLine,
    'arrow-right': ArrowRight,
    'book-open': BookOpen,
    box: Box,
    'calendar-plus': CalendarPlus,
    car: Car,
    'cloud-abode': CloudAbode,
    check: Check,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'circle-alert': CircleAlert,
    'circle-help': CircleHelp,
    clock: Clock,
    compass: Compass,
    copy: Copy,
    database: Database,
    download: Download,
    'ellipsis-vertical': EllipsisVertical,
    eye: Eye,
    'external-link': ExternalLink,
    folder: Folder,
    'folder-open': FolderOpen,
    'folder-plus': FolderPlus,
    github: Github,
    globe: Globe,
    heart: Heart,
    home: Home,
    image: Image,
    inbox: Inbox,
    layers: Layers,
    'layout-grid': LayoutGrid,
    link: Link,
    list: List,
    loader: Loader2,
    maximize: Maximize2,
    minus: Minus,
    palette: Palette,
    pin: Pin,
    'pin-off': PinOff,
    pencil: Pencil,
    plus: Plus,
    'refresh-cw': RefreshCw,
    'rotate-ccw': RotateCcw,
    save: Save,
    search: Search,
    share: Share2,
    settings: Settings,
    'sliders-horizontal': SlidersHorizontal,
    smartphone: Smartphone,
    sparkles: Sparkles,
    square: Square,
    'square-arrow-up-left': SquareArrowUpLeft,
    star: Star,
    sun: Sun,
    'thumbs-up': ThumbsUp,
    'trash-2': Trash2,
    'triangle-alert': TriangleAlert,
    user: User,
    video: Video,
    'volume-2': Volume2,
    'volume-x': VolumeX,
    x: X,
    zap: Zap
} satisfies Record<string, Component>

export type WwIconName = keyof typeof wwIcons
