import type { Component } from 'vue'
import {
    AlignHorizontalSpaceBetween,
    AlignVerticalJustifyCenter,
    AlignVerticalJustifyEnd,
    AlignVerticalJustifyStart,
    AlignVerticalSpaceBetween,
    TextAlignCenter,
    TextAlignEnd,
    TextAlignStart,
    AppWindow,
    ArrowDownAZ,
    ArrowDownFromLine,
    ArrowLeft,
    ArrowRight,
    ArrowUpToLine,
    BookOpen,
    Box,
    CalendarPlus,
    Car,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircleAlert,
    CircleHelp,
    ClipboardPaste,
    Clock,
    Compass,
    Copy,
    Database,
    Columns2,
    Disc3,
    Download,
    Eraser,
    EllipsisVertical,
    Eye,
    EyeOff,
    ExternalLink,
    Folder,
    FolderOpen,
    FolderPlus,
    GalleryVertical,
    Hand,
    Globe,
    Heart,
    Home,
    Image,
    Inbox,
    Layers,
    LayoutGrid,
    LayoutPanelLeft,
    PanelRight,
    Link,
    List,
    ListMusic,
    Loader2,
    Maximize2,
    MessageCircle,
    Minus,
    Paintbrush,
    Palette,
    Pin,
    PinOff,
    Pencil,
    Play,
    Pause,
    Plus,
    RefreshCw,
    Redo2,
    RotateCcw,
    Rows2,
    Save,
    Search,
    Share2,
    Settings,
    Shuffle,
    SlidersHorizontal,
    Smartphone,
    Sparkles,
    Square,
    SquareArrowUpLeft,
    Star,
    Sun,
    ThumbsUp,
    Trash2,
    TriangleAlert,
    Undo2,
    Ungroup,
    User,
    Video,
    Volume2,
    VolumeX,
    X,
    Zap
} from '@lucide/vue'
import { Github } from './Github'

/** 全局描边宽度（px），absoluteStrokeWidth 下视觉更一致 */
export const WW_ICON_STROKE = 1.5

export const wwIcons = {
    'align-left': TextAlignStart,
    'align-center-h': TextAlignCenter,
    'align-right': TextAlignEnd,
    'align-top': AlignVerticalJustifyStart,
    'align-center-v': AlignVerticalJustifyCenter,
    'align-bottom': AlignVerticalJustifyEnd,
    'align-distribute-h': AlignHorizontalSpaceBetween,
    'align-distribute-v': AlignVerticalSpaceBetween,
    'app-window': AppWindow,
    'arrow-down-a-z': ArrowDownAZ,
    'arrow-down-from-line': ArrowDownFromLine,
    'arrow-left': ArrowLeft,
    'arrow-up-to-line': ArrowUpToLine,
    'arrow-right': ArrowRight,
    'book-open': BookOpen,
    box: Box,
    'calendar-plus': CalendarPlus,
    car: Car,
    check: Check,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'chevron-up': ChevronUp,
    'circle-alert': CircleAlert,
    'circle-help': CircleHelp,
    clock: Clock,
    'clipboard-paste': ClipboardPaste,
    compass: Compass,
    copy: Copy,
    'columns-2': Columns2,
    database: Database,
    'disc-3': Disc3,
    download: Download,
    'ellipsis-vertical': EllipsisVertical,
    eye: Eye,
    'eye-off': EyeOff,
    'external-link': ExternalLink,
    folder: Folder,
    'folder-open': FolderOpen,
    'folder-plus': FolderPlus,
    'gallery-vertical': GalleryVertical,
    github: Github,
    globe: Globe,
    heart: Heart,
    hand: Hand,
    home: Home,
    image: Image,
    inbox: Inbox,
    layers: Layers,
    'layout-grid': LayoutGrid,
    'layout-panel-left': LayoutPanelLeft,
    'layout-panel-right': PanelRight,
    link: Link,
    list: List,
    'list-music': ListMusic,
    loader: Loader2,
    maximize: Maximize2,
    'message-circle': MessageCircle,
    minus: Minus,
    paintbrush: Paintbrush,
    palette: Palette,
    pin: Pin,
    eraser: Eraser,
    'pin-off': PinOff,
    pencil: Pencil,
    play: Play,
    pause: Pause,
    plus: Plus,
    'refresh-cw': RefreshCw,
    redo: Redo2,
    'rotate-ccw': RotateCcw,
    rows: Rows2,
    save: Save,
    search: Search,
    share: Share2,
    settings: Settings,
    shuffle: Shuffle,
    'sliders-horizontal': SlidersHorizontal,
    smartphone: Smartphone,
    sparkles: Sparkles,
    square: Square,
    'square-arrow-up-left': SquareArrowUpLeft,
    star: Star,
    sun: Sun,
    'thumbs-up': ThumbsUp,
    'trash-2': Trash2,
    'triangle-alert': TriangleAlert,
    undo: Undo2,
    ungroup: Ungroup,
    user: User,
    video: Video,
    'volume-2': Volume2,
    'volume-x': VolumeX,
    x: X,
    zap: Zap
} satisfies Record<string, Component>

export type WwIconName = keyof typeof wwIcons
