import type { Component } from 'vue'
import {
  ArrowDownAZ,
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Box,
  CalendarPlus,
  Car,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleHelp,
  Clock,
  Compass,
  Copy,
  Database,
  Download,
  EllipsisVertical,
  ExternalLink,
  Folder,
  FolderOpen,
  FolderPlus,
  Github,
  Globe,
  Heart,
  Home,
  Image,
  Inbox,
  LayoutGrid,
  List,
  Loader2,
  Maximize2,
  Minus,
  Palette,
  Pencil,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  Share2,
  Settings,
  Smartphone,
  Sparkles,
  Square,
  Star,
  Sun,
  Trash2,
  TriangleAlert,
  User,
  Video,
  X,
  Zap
} from 'lucide-vue-next'

/** 全局描边宽度（px），absoluteStrokeWidth 下视觉更一致 */
export const WW_ICON_STROKE = 1.5

export const wwIcons = {
  'arrow-down-a-z': ArrowDownAZ,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'book-open': BookOpen,
  box: Box,
  'calendar-plus': CalendarPlus,
  car: Car,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-help': CircleHelp,
  clock: Clock,
  compass: Compass,
  copy: Copy,
  database: Database,
  download: Download,
  'ellipsis-vertical': EllipsisVertical,
  'external-link': ExternalLink,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  github: Github,
  globe: Globe,
  heart: Heart,
  home: Home,
  image: Image,
  inbox: Inbox,
  'layout-grid': LayoutGrid,
  list: List,
  loader: Loader2,
  maximize: Maximize2,
  minus: Minus,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  search: Search,
  share: Share2,
  settings: Settings,
  smartphone: Smartphone,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  sun: Sun,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  user: User,
  video: Video,
  x: X,
  zap: Zap
} satisfies Record<string, Component>

export type WwIconName = keyof typeof wwIcons

export function resolveWwIcon(name: string): Component | undefined {
  return wwIcons[name as WwIconName]
}
