export type { IMusicPlatformGateway } from './IMusicPlatformGateway'
export type { IMusicPlatformService } from './IMusicPlatformService'
export { DynamicModuleGateway } from './dynamicModuleGateway'
export { MusicPlatformManager } from './MusicPlatformManager'
export { PlatformSessionStore } from './sessionStore'
export { parseBrowseId } from './browseId'
export { KugouPlatformService } from './kugou/kugouPlatformService'
export { NeteasePlatformService } from './netease/neteasePlatformService'
export * from './types'
