/**
 * 云斋展厅参数 — 对齐 su7-replica 实时渲染（烘焙 lightMap + emissive 灯板 + Bloom）
 */
export const SHOWROOM_LIGHTING = {
  useHdrEnvironment: true,
  cameraFov: 33.4,
  cameraFovRush: 36,
  orbitTarget: { x: 0, y: 0.8, z: 0 } as const,
  /** su7 Car：仅 bodyMat.envMapIntensity 动画 */
  bodyEnvMapIntensity: 1,
  bodyEnvMapIntensityRush: 10,
  /** DynamicEnv 混合强度 */
  envIntensity: 1,
  envIntensityRush: 0.01,
  wheelEnvIntensity: 0.36,
  chromeEnvIntensity: 0.44,
  glassEnvIntensity: 0.5,
  defaultEnvIntensity: 0.38,
  envWeight: 1,
  envFadeInDuration: 4,
  envFadeInDelay: 0.5,
  envWeightFadeOverlap: 2.5,
  bodyAoIntensity: 0.45,
  /** 平面反射强度（地板 shader，su7 默认 25） */
  floorReflectIntensity: 25,
  floorReflectMix: 1,
  floorReflectRoughnessMul: 4,
  /** 地板 lightMap（聚光遮罩 + 软接触阴影，su7 无 shadowMap） */
  floorLightMapIntensity: 1,
  /** lightMap pow，≈1 保留烘焙软阴影 */
  floorSpotContrast: 1,
  floorAoIntensity: 1,
  /** su7 仅用 GLTF emissive 灯板，不用实时 RectArea/Spot */
  enableRealtimeLightRig: false,
  rectAreaLightIntensity: 0,
  spotLightIntensity: 0,
  spotAngle: 0.42,
  spotPenumbra: 0.42,
  spotDistance: 14,
  spotHeight: 7.5,
  spotOffset: { x: 0, z: 1.2 } as const,
  /** su7 无 WebGL shadowMap；接触阴影来自 lightMap 烘焙 */
  enableSpotShadows: false,
  spotShadowMapSize: 2048,
  spotShadowBias: -0.00015,
  spotShadowNormalBias: 0.025,
  spotShadowRadius: 8,
  realtimeSpotWeight: 0,
  keyLightEmissive: 0.85,
  /** su7 Postprocessing：intensity 1 / threshold 0 */
  bloomIntensity: 1,
  bloomLuminanceSmoothing: 1.6,
  bloomLuminanceThreshold: 0,
  bloomIntensityRush: 2,
  bloomLuminanceSmoothingRush: 0.4,
  toneMappingExposure: 1,
  enableSSR: false,
  ssrIntensity: 0.42,
  enableSSAO: false,
  cinematic: false,
  enableSMAA: false,
  enableCinematicGrade: false,
  enableTemporalAA: false,
  floorTintMul: 3,
  lightFadeInDuration: 4,
  lightFadeInDelay: 1,
  rushSpeedMid: 4,
  rushSpeedMax: 10,
  rushSpeedMidDuration: 2,
  rushSpeedMaxDuration: 4,
  wheelSpinPerSpeed: 1.875,
  rushSceneCaptureDelay: 1,
  rushEnvBoostDuration: 4,
  rushLightFadeDuration: 1,
  rushFloorLerpDuration: 4,
  rushEnvFadeDuration: 1,
  rushFovDuration: 2,
  rushExitSpeedDuration: 2,
  rushExitRestoreDuration: 4,
  cameraShakeRush: 1,
  reflectorResolution: 1024
} as const
